name: Auto Commit 

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set Git Identity   # <-- IMPORTANT FIX
      run: |
        git config --global user.email "shahidsayyed0212@gmail.com"
        git config --global user.name "sayyadshahid"

    - name: Generate Random Commits
      run: |
        NUM=$(( RANDOM % 17 + 4 ))    
        echo "Generating $NUM commits today!"
        for i in $(seq 1 $NUM); do
          echo "$(date)" >> commits-log.txt
          git add commits-log.txt
          git commit -m "Auto commit: $(date)"
        done

    - name: Push Changes
      run: |
        git push
